### ISSUE TITLE
Can only elf binary be analyzed? I tried to run cgi with no result.

### ISSUE THREAD

**Issue by Jackey0** [fxc233/fdcalls#1]

**Comment by Jackey0** [comment]
![image](https://github.com/fxc233/fdcalls/assets/52018740/2c4c399a-e167-4b16-9cee-e3423892053b)

**Comment by fxc233** [comment]
In theory, it supports the analysis of CGI. Can you provide specific firmware? I may need to analyze them in detail.

**Comment by fxc233** [comment]
Thanks for your reply. When I find the bug, I will provide you with feedback.

**Comment by fxc233** [comment]
I regret to inform you that this product is currently based on Radare2, which does not support the mips64 architecture very well.  You can try to analyze the architecture of arm and mips.

**Comment by fxc233** [comment]
If you don't have other questions, I will close the issue.

**Comment by Jackey0** [comment]
ok，very thanks ！
